### ISSUE TITLE
"Bandcamp Desktop cannot be Opened because of a problem" | MacOS Catalina 

### ISSUE THREAD

**Issue by vivekteega** [themagiulio/bandcamp-desktop#7] opened 2020-12-01 23:06 UTC
There seems to be a php dependency missing in the MacOS binary file 

```
Process:               Bandcamp Desktop [3996]
Path:                  /private/var/folders/*/Bandcamp Desktop.app/Contents/MacOS/Bandcamp Desktop
Identifier:            com.themagiulio.bandcamp-desktop
Version:               2.3.0 (2.3.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Bandcamp Desktop [3996]
User ID:               501

Date/Time:             2020-12-02 04:30:22.135 +0530
OS Version:            Mac OS X 10.15.7 (19H15)
Report Version:        12
Bridge OS Version:     4.6 (17P6610)
Anonymous UUID:        2FE04525-DDE1-C9A2-A9E6-BDAE302EA66E


Time Awake Since Boot: 9600 seconds

System Integrity Protection: enabled

Notes:                 Translocated Process

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /private/var/folders/*/Bandcamp Desktop.app/Contents/MacOS/Bandcamp Desktop
  Reason: no suitable image found.  Did find:
	/private/var/folders/ln/sqt67gfn4jn0fwnth796ks3r0000gn/T/AppTranslocation/7A98EEEC-61C5-4012-8420-D5E80B204314/d/Bandcamp Desktop.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: file too short
	/private/var/folders/ln/sqt67gfn4jn0fwnth796ks3r0000gn/T/AppTranslocation/7A98EEEC-61C5-4012-8420-D5E80B204314/d/Bandcamp Desktop.app/Contents/MacOS/../Frameworks/Electron Framework.framework/Electron Framework: stat() failed with errno=1

Binary Images:
       0x10ea50000 -        0x10ea77ff3 +com.themagiulio.bandcamp-desktop (2.3.0 - 2.3.0) <5CF444E6-280A-33A3-87FF-B56A6B4EC25C> /var/folders/*/Bandcamp Desktop.app/Contents/MacOS/Bandcamp Desktop
       0x1100e4000 -        0x110175f47  dyld (750.6) <1D318D60-C9B0-3511-BE9C-82AFD2EF930D> /usr/lib/dyld

Model: MacBookPro16,1, BootROM 1037.147.4.0.0 (iBridge: 17.16.16610.0.0,0), 8 processors, 8-Core Intel Core i9, 2.4 GHz, 64 GB, SMC 
Graphics: kHW_IntelUHDGraphics630Item, Intel UHD Graphics 630, spdisplays_builtin
Graphics: kHW_AMDRadeonPro5500MItem, AMD Radeon Pro 5500M, spdisplays_pcie_device, 8 GB
Memory Module: BANK 0/ChannelA-DIMM0, 32 GB, DDR4, 2667 MHz, Micron, -
Memory Module: BANK 2/ChannelB-DIMM0, 32 GB, DDR4, 2667 MHz, Micron, -
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Apr  7 2020 13:09:12 version 9.30.357.41.32.5.49 FWID 01-617711e7
Bluetooth: Version 7.0.6f7, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB3.0 Hub
USB Device: USB 10/100/1000 LAN
USB Device: USB 3.1 Bus
USB Device: USB2.0 Hub
USB Device: Scarlett 2i2 USB
USB Device: USB Receiver
USB Device: Anker USB-C Hub Device
USB Device: Apple T2 Bus
USB Device: Composite Device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 55.3
Thunderbolt Bus: MacBook Pro, Apple Inc., 55.3

```

**Comment by themagiulio** [comment] 2020-12-15 13:17
Hi,
from when we talked about it in Reddit, did you manage to build the app from source on your own machine?

**Comment by tub** [comment] 2021-01-21 11:42
It looks like all the symlinks for the framework versions are just text-files with paths in them:
```cat /Users/blah/Bandcamp\ Desktop.app/Contents/Frameworks/Electron\ Framework.framework/Electron\ Framework
Versions/Current/Electron Framework%```

**Comment by themagiulio** [comment] 2021-01-21 15:53
Since when I used to package the app from Mac OS it worked fine, I think the problem is that I'm packaging it from a GNU Linux distro. I'll try to find a way to fix that bug. Any advice is accepted.

**Comment by vivekteega** [comment] 2021-01-23 10:27
Hey dude @themagiulio , apologies to the late reply 

I packed the app on the macOS Catalina 10.15.7 and it is working for me. This is the dmg file https://drive.google.com/file/d/1l8wVDvYniN_ShYoQyTbgbqL8qw8kBTqr/view?usp=sharing

I followed the your instruction from the other post 

> So that is what you need to do:
> 
> 1. Download and install node.
> 2. Download the source code of Bandcamp Desktop by clicking here.
> 3. Open the terminal in the source folder and type npm install.
> 4. Edit the file package.json and in the script > build section substitute -l with -m. In the same file in build > mac > target, substitute tar.gz with dmg.
> 5. Once you do that you need to run the following command: npm run-script build.
> 6. A dist folder will be created in the source directory and in it you should find the dmg file of the app.

**Comment by themagiulio** [comment] 2021-01-23 11:35
Thank you so much to have packaged the app.
As I stated in the duplicate of that issue (now closed), I added it in the release files.

I leave this issue open for further communications.

**Comment by ike1985** [comment] 2021-01-23 17:48
> Hey dude @themagiulio , apologies to the late reply
> 
> I built the app on the macOS Catalina 10.15.7 and it is working for me. This is the dmg file https://drive.google.com/file/d/1l8wVDvYniN_ShYoQyTbgbqL8qw8kBTqr/view?usp=sharing
> 
> I followed the your instruction from the other post
> 
> > So that is what you need to do:
> > 
> > 1. Download and install node.
> > 2. Download the source code of Bandcamp Desktop by clicking here.
> > 3. Open the terminal in the source folder and type npm install.
> > 4. Edit the file package.json and in the script > build section substitute -l with -m. In the same file in build > mac > target, substitute tar.gz with dmg.
> > 5. Once you do that you need to run the following command: npm run-script build.
> > 6. A dist folder will be created in the source directory and in it you should find the dmg file of the app.

THANK YOU SO MUCH @vivekteega , it is working flawlessly.  god bless you sir.  Thank you @themagiulio for all your work as well.

**Comment by vivekteega** [comment] 2021-01-24 13:50
> Thank you so much to have packaged the app.
> As I stated in the duplicate of that issue (now closed), I added it in the release files.
> 
> I leave this issue open for further communications.

Thanks for all the work on the app dude :)

**Comment by themagiulio** [comment] 2021-03-04 21:10
Hey, I built a new dmg file for the latest version and it should work!
I can consider this issue as resolved, but if you still have problems don't hesitate to comment!

**Closed by themagiulio** 2021-03-04 21:10 UTC
Labels: bug
