### ISSUE TITLE
Please help, cannot install MAC

### ISSUE THREAD

**Issue by ike1985** [themagiulio/bandcamp-desktop#13] opened 2021-01-18 20:36 UTC
I am not a programmer or developer and I tried my best to install this via the provided instructions but there is an error with the installation file: 

![Screen Shot 2021-01-18 at 3 34 27 PM](https://user-images.githubusercontent.com/77642294/104960675-b6b7b980-59a2-11eb-99ac-678eb20e2856.png)

I have been waiting for a desktop Bandcamp app or years, thank you for all your hardworking, if there is any way you could fix this I would greatly appreciate it.  Thank You

I am on High Sierra v10.3.6

**Comment by themagiulio** [comment] 2021-01-18 21:23
Hi @ike1985,
thanks for reporting the bug and for your support! The problem you have find out seems a duplicate of #7.
Unfortunately I don't have Mac OS installed on my pc, that means I can't replicate your steps and find a solution on my own.
However, I'll try to guide through fixing the bug.

The first think I suggest is trying to extract the tar.gz archive using terminal.

1. Open the terminal.
2. Using the `cd` command go to the directory where the archive is located (ex. `cd \Desktop`).
3. Run `tar -xzvf  Bandcamp-Desktop-2.3.5-mac.tar.gz` (if you renamed the archive you need to specify the new name).
4. After that you will be able to find the app in the same directory where the archive is located. Try to open it and then let me know if the problem has been solved.

**Comment by ike1985** [comment] 2021-01-21 16:46
So it allowed me to extract it and I can now see a Bandcamp icon in the folder, the problem is I am getting the same error again when I try to open the extracted app.  thank you for the help.

**Comment by themagiulio** [comment] 2021-01-21 17:07
Okay, so I'll try to find a better method to package the Mac OS app.

If you want to use the app now I suggest to package it on your machine following the instructions given in the [README.md](https://github.com/themagiulio/bandcamp-desktop/blob/master/README.md).

So that is what you need to do:
1. Download and install node.
2. Download the source code of Bandcamp Desktop by clicking [here](https://github.com/themagiulio/bandcamp-desktop/archive/master.zip).
3. Open the terminal in the source folder and type `npm install`.
4. Edit the file `package.json` and in the `script > build` section substitute `-l` with `-m`. In the same file in `build > mac > target`, substitute `tar.gz` with `dmg`.
5. Once you do that you need to run the following command: `npm run-script build`.
6. A `dist` folder will be created in the source directory and in it you should find the dmg file of the app.

Another "solution" could be using an old version of Bandcamp Desktop: [download it by clicking here](https://github.com/themagiulio/bandcamp-desktop/releases/download/v2.2.0/Bandcamp-Desktop-2.2.0.dmg).

I will let you know when I'll fix the problem.

**Comment by vivekteega** [comment] 2021-01-23 10:27
I packed the app on the macOS Catalina 10.15.7 and it is working for me. This is the dmg file https://drive.google.com/file/d/1l8wVDvYniN_ShYoQyTbgbqL8qw8kBTqr/view?usp=sharing

**Comment by themagiulio** [comment] 2021-01-23 11:27
Thanks for building the app!
I'm going to add it to the Release files.

I hope to find a better solution for future releases.

**Comment by themagiulio** [comment] 2021-01-23 11:28
In order to avoid confusions I'm going to close this issue.

Every other communications about the MacOS bug will be reported in #7.

**Closed by themagiulio** 2021-01-23 11:28 UTC
Labels: duplicate
